services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    command: ['redis-server', '--save', '60', '1', '--appendonly', 'yes']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - ./redisinsight_data:/db
    depends_on:
      redis:
        condition: service_healthy
  
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/video_game_store_api
      - REDIS=redis
  mongo:
    image: mongo:6.0
#volumes:
#  redis_data:
#  redisinsight_data: