version: "3.8"

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    ports:
      - "8080:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=vgstore
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mongo_data:
  redis_data:
  redisinsight_data:
