version: '3.8'

services:
  api_mvoies_series:
    build: ./api_mvoies_series
    container_name: api_mvoies_series
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TTL_SECONDS=120
    volumes:
      - ./api_mvoies_series:/app
      - /app/node_modules

  api_users:
    build: ./api_users
    container_name: api_users
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - REDIS_URL=redis://redis:6379/0
      - CACHE_TTL_SECONDS=120
    volumes:
      - ./api_users:/app   
      - /app/node_modules

  mongodb:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    command: ['redis-server', '--save', '60', '1', '--appendonly', 'yes']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - ./redisinsight_data:/db
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mongo_data:
  redis_data:
  redisinsight_data:
